name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  release:
    name: Create Release
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.22'

    - name: Run tests
      run: go test -v ./...

    - name: Build binaries
      run: |
        # Linux
        GOOS=linux GOARCH=amd64 go build -o bin/ape_my-linux-amd64 ./cmd/ape_my
        GOOS=linux GOARCH=arm64 go build -o bin/ape_my-linux-arm64 ./cmd/ape_my

        # macOS
        GOOS=darwin GOARCH=amd64 go build -o bin/ape_my-darwin-amd64 ./cmd/ape_my
        GOOS=darwin GOARCH=arm64 go build -o bin/ape_my-darwin-arm64 ./cmd/ape_my

        # Windows
        GOOS=windows GOARCH=amd64 go build -o bin/ape_my-windows-amd64.exe ./cmd/ape_my

    - name: Create checksums
      run: |
        cd bin
        sha256sum ape_my-* > checksums.txt

    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          bin/ape_my-linux-amd64
          bin/ape_my-linux-arm64
          bin/ape_my-darwin-amd64
          bin/ape_my-darwin-arm64
          bin/ape_my-windows-amd64.exe
          bin/checksums.txt
        draft: false
        prerelease: false
        generate_release_notes: true
